server:
  port: 8091

spring:
  application:
    name: yousee-clouds-user
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.126.158:3307/yousee?serverTimezone=Asia/Shanghai
    username: root
    password: 'Proytree012'
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: yousee-clouds-user-hikari
      max-lifetime: 1800000
      read-only: false
      connection-timeout: 30000
#  security:
#    user:
#      name: root
#      password: tiger

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer:tiger@peer8761:8761/eureka/

info:
  app:
    name: @project.artifactId@

management:
  endpoint:
    env:
      enabled: true

logging:
  level:
    yousee: debug
    com: debug
    org: debug
