server:
  port: 8093
  tomcat:
    max-connections: 10000
    max-threads: 1000

spring:
  application:
    name: yousee-clouds-video
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer:tiger@peer8761:8761/eureka/
  instance:
    prefer-ip-address: true

fegin:
  hystrix:
    enabled: true

logging:
  level:
    yousee: debug
    com: debug
